# NOTE: Create a copy of this file, and save it as config.ini

[datasets.path]
train = <your_path_to_the_directory_with_the_training_images>
test = <your_path_to_the_directory_with_the_test_images>
extra = <your_path_to_the_directory_with_the_extra_images>
pickle = <your_path_to_the_directory_with_the_pickle_files>
